---
title Project-Course-2
author Gustavo I. Camilo
date 11102019
output html_document
---

```{r}
require(tidyverse)
require(dplyr)
require(pacman)
require(ggplot2)
```

#Carregando e Lendo os dados
```{r}
StormData <- tbl_df(read.csv(file.choose(), header = T, sep = ","))
```

#
```{r}
#
StormData.fatalities <- subset(StormData, !StormData$FATALITIES == 0, select = c(EVTYPE, FATALITIES))

#
StormData.injuries <- subset(stormEvent,!stormEvent$INJURIES == 
    0, select = c(EVTYPE, INJURIES))

#
EUA_economic <- subset(StormData, !StormData$PROPDMG == 0 & !StormData$CROPDMG == 
    0, select = c(EVTYPE, PROPDMG, PROPDMGEXP, CROPDMG, CROPDMGEXP))

```


## 1- Across the United States, which types of events (as indicated in the 'EVTYPE' variable) are most harmful with respect to population health?



```{r}

StormData.fatalities <- aggregate(StormData.fatalities$FATALITIES, by = list(StormData.fatalities$EVTYPE), 
    FUN = sum)
colnames(StormData.fatalities) <- c("EVTYPES", "FATALITIES")
 StormData.fatalities <- StormData.fatalities[order(StormData.fatalities$FATALITIES, decreasing = TRUE), ][1:10, ]
 
 #
 fatalities <- ggplot() + geom_bar(data = StormData.fatalities, aes(x = EVTYPES, 
    y = FATALITIES, fill = interaction(FATALITIES, EVTYPES)), stat = "identity", 
    show.legend = F) + theme(axis.text.x = element_text(angle = 30, hjust = 1)) + 
    xlab("Harmful Events") + ylab("No. of fatailities") + ggtitle("Top 5 weather events causing fatalities") + 
    theme(axis.text.x = element_text(angle = 30, hjust = 1))

```


```{r}


StormData.injuries <- aggregate(StormData.injuries$INJURIES, by = list(StormData.injuries$EVTYPE), FUN = sum)
colnames(StormData.injuries) <- c("EVTYPES","INJURIES")  
StormData.injuries <- StormData.injuries[order(INJURIES, decreasing = T,) ][1:10, ]

#
injuries <- ggplot() + geom_bar(data = StormData.injuries, aes(x = EVTYPES, y = INJURIES, 
    fill = interaction(INJURIES, EVTYPES)), stat = "identity", show.legend = F) + 
    theme(axis.text.x = element_text(angle = 30, hjust = 1)) + xlab("Harmful Events") + 
    ylab("No. of Injuries") + ggtitle("Top 5 weather events causing Injuries") + 
    theme(axis.text.x = element_text(angle = 30, hjust = 1))


```

#
```{r}

# 
grid.arrange(fatalities, injuries, ncol = 2)

```
## 2- Across the United States, which types of events have the greatest economic consequences?

```{r}
##Verificando quais limpezas precisamos fazer na coluna 'PROPDMGEXP' indentificado através do levels
head(StormData$PROPDMGEXP)

##Verificando quais limpezas precisamos fazer na coluna 'PROPDMGEXP' indentificado através do levels
head(StormData$CROPDMGEXP)
```
```{r}
##Limpando os dados das tabelas verificadas

StormData <-  StormData %>% mutate_at(vars(PROPDMGEXP,CROPDMGEXP), 
               funs(as.numeric(recode(.,'0'=1,'1'=10,'2'=10^2,'3'=10^3,'4'=10^4,'5'=10^5,
                                             '6'=10^6,'7'=10^7,'8'=10^8, 'B'=10^9,
                                             'h'=1^2,'H'=1^2, 'k'=10^3,'K'=10^3,'m'=10^6,'M'=10^6,
                                             ' '=0,'-'=0,'?'=0,'+'=0))))                            


```


```{r}

PROPDMG <- EUA_economic$PROPDMG * EUA_economic$PROPDMGEXP
CROPDMG <- EUA_economic$CROPDMG * EUA_economic$CROPDMGEXP

EUA_economic$TotalPropCrop <- PROPDMG + CROPDMG

EUA_economic <- aggregate(EUA_economic$TotalPropCrop, by = list(EUA_economic$EVTYPE), FUN = sum) 

colnames(EUA_economic) <- c("EVTYPE", "TotalPropCrop")

EUA_economic <- EUA_economic[order(EUA_economic$TotalPropCrop, decreasing = T), ][1:10, ]

head(EUA_economic , n = 10)
```
